"""add login tokens table for short magic links

Revision ID: 5f3af3cbc53b
Revises: 6aa51d72d4d0
Create Date: 2025-10-26 19:52:29.921133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3af3cbc53b'
down_revision: Union[str, None] = '6aa51d72d4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

