"""empty message

Revision ID: bef5705e47a8
Revises: 5f3af3cbc53b
Create Date: 2025-10-26 19:59:31.111453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef5705e47a8'
down_revision: Union[str, None] = '5f3af3cbc53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_id'), 'login_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_login_tokens_telegram_id'), 'login_tokens', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_login_tokens_token'), 'login_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_tokens_token'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_telegram_id'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_id'), table_name='login_tokens')
    op.drop_table('login_tokens')
    # ### end Alembic commands ###

